### ISSUE TITLE
MuckMobSpawner bug

### ISSUE THREAD

**Issue by STENKLER132** [oliviersamson/Muck-BugFixes#1] opened 2024-05-07 09:05 UTC
There is a bug with this mod where, when u spawn some mobs, u wont be able to kill them, or u wont be able to kill other mobs. When this happends, if u are multiplayer, other players cant see u, nor the mobs u spawned, and nothing can kill those mobs. Its also happening in singleplayer. When bug happend, there is a text in console that says attacking. stoponattack: False. Bug is always happening only when u use the mod. It can be activated, but nothing will happend, but when u spawn the mobs, it will be bugged. I dont have any ss or anything, i tryed to search up if somebody had same issues, but i didnt find anything. Im not sure if some other mods are the issue with this one, or its this mod... Thanks =)

**Comment by oliviersamson** [comment] 2024-05-07 18:42
@STENKLER132 

Hello. Thanks for the input.

I was able to reproduce the problem and will be looking into it. 

However, it is possible that the MuckMobSpawner mod is not compatible with my mod due to changes made by both of them. I will be investigating this issue but might not be able to resolve it if the only solution is to change the MuckMobSpawner mod.

**Comment by STENKLER132** [comment] 2024-05-07 19:02
Its not about ur mod. I was posting here in case myb u can fix that mod, so that doesnt happend anymore... I am using alot of modes, but even when im using no modes at all, only that one, it will be happening. Im not sure whats the problem, myb its problem in the mod: MuckModSpawner, but if u can fix it anyhow, i would be very happy. Thanks once again! Cheers

**Comment by oliviersamson** [comment] 2024-05-07 19:37
@STENKLER132 

Yes, this checks out with the result of my investigation.

From what I could see, the MuckMobSpawner mod doesn't properly use and manage mob IDs (he's not using the game MobManager.GetNextId() method). The result is that the mod will try to spawn a new mob with an ID that already belongs to an existing mob, thus causing the issue.

I could totally patch this mod, as I did with the Terrain-SettingsApi mod. However, I think it would be best to contact the MuckMobSpawner mod author and see if he can fix it himself. If not, then I can make another mod to patch his.

**Comment by STENKLER132** [comment] 2024-05-07 19:48
I tryed to contact the author, but i cant find his page, its deleted... I will very much appreciate if u can fix it, but if its something hard, or time consuming, u dont have to do it, its just making game better cuz at some point there is no more things to kill. Thanks! Wish u a good night! =)

**Comment by oliviersamson** [comment] 2024-05-07 20:20
@STENKLER132 

Alright, I'll try contacting the author too and see what I can do if he does't respond. It should be an easy fix for me too if it comes to me having to make a patch for it.

However, please refrain from creating an issue for another mod on here. This mod page is strickly for bugs contained in the original game and any issues with the BugFixes mod itself.

If you have any other requests like this one, I would rather prefer that you contact me on discord (ID: 110851337314381824) and I will see what I can do.

**Closed as not planned by oliviersamson** 2024-05-07 20:20 UTC
Labels: Bug in Mod
